//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDRESTful_Service.Models
{
    using System;
    
    public partial class BuildBestFitItem
    {
        public int itemID { get; set; }
        public string typeID { get; set; }
        public string itemName { get; set; }
        public string typeName { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
    }
}
